name: "Broken Link"
description: Report a broken or redirected link
labels: ["bug", "documentation"]
body:
  - type: input
    id: file
    attributes:
      label: File
      placeholder: "e.g., 08_Model_Evaluation_and_Validation.md"
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link URL
      placeholder: "https://..."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Where in the document is this link used?