name: "Content Suggestion"
description: Propose improvements to explanations, structure, or references
labels: ["enhancement", "documentation"]
body:
  - type: input
    id: module
    attributes:
      label: Module
      placeholder: "e.g., 14_PyTorch_Fundamentals.md"
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the change and why it's beneficial.
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References
      description: Include durable sources (docs, papers).