name: "Typo / Grammar"
description: Report a typo or grammatical issue
labels: ["documentation"]
body:
  - type: input
    id: file
    attributes:
      label: File
      description: Which file has the typo?
      placeholder: "e.g., 05_Supervised_Regression.md"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: What should be corrected?
      placeholder: "Original text -> Suggested fix"
    validations:
      required: true